import "./globals.css";

export const metadata = {
  title: "Photo Gallery",
  description: "Generated by Next.js",
};

export default function RootLayout(props: {
  children: React.ReactNode;
  parallel: React.ReactNode;
}) {
  return (
    <html lang="ru">
      <body>
        {props.children}
        {props.parallel}
      </body>
    </html>
  );
}
